# -*- coding: utf-8 -*-
"""Implementação para Reprodução da Descrição Inicial e Cálculo dos Indicadores de Confiabilidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzHAHCkN2HJgvyrYSu0TD3sDsl9oHP1A
"""

#Descição Inicial dos Dados
df.info()


# Identifica os índices onde ocorreu falha
falhas = df[df['falha'] == 1]['udi'].values


# Se houver menos de duas falhas, MTBF não pode ser calculado
if len(falhas) < 2:
    mtbf = None
else:
    intervalos = np.diff(falhas)
    mtbf = intervalos.mean()


print(f"MTBF: {mtbf}")




# Taxa de falha = número de falhas / tempo total observado
num_falhas = df['falha'].sum()
tempo_total = df['udi'].max() - df['udi'].min() + 1
taxa_falha = num_falhas / tempo_total


print(f"Taxa de Falha: {taxa_falha}")