# -*- coding: utf-8 -*-
"""Implementação para Reprodução da Análise Exploratória dos Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnboIpbNzrTVwRKvAMExoqQXzIyNPlZq
"""

#importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# Leitura do CSV
df = pd.read_csv('/content/data_overall.csv')


#Informações descritivas gerais
df.info()


# Estatísticas gerais
desc = df.describe()


# Exibe a tabela de dados faltantes
print('\nTabela de Dados Faltantes:')
missing_data = pd.DataFrame({
    'Coluna': df.columns,
    'Quantidade Faltante': df.isnull().sum(),
    'Percentual Faltante (%)': (df.isnull().sum() / len(df)) * 100
})
missing_data


# Contagem de falhas
print('\nDistribuição da variável alvo (falha):')
print(df['falha'].value_counts())


# Visualizações de Histogramas
features = ['temperatura do ar', 'temperatura do processo', 'velocidade de rotação', 'torque', 'desgaste de ferramenta']


plt.figure(figsize=(15, 8))
for i, col in enumerate(features):
    plt.subplot(2, 3, i+1)
    sns.histplot(df[col], kde=True, bins=30)
    plt.title(f'Histograma de {col}')
plt.tight_layout()
plt.show()


#Analise de Correlação
plt.figure(figsize=(15, 8))
for i, col in enumerate(features):
    plt.subplot(2, 3, i+1)
    sns.boxplot(y=df[col])
    plt.title(f'Boxplot de {col}')
plt.tight_layout()
plt.show()


#Dispersão entre as variaveis mais correlacionadas
sns.pairplot(df[features + ['falha']], hue='falha', diag_kind='kde')
plt.show()